[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "algrow"
version = "0.3"
authors = [
  { name="Marcus McHale", email="marcus.mchale@universityofgalway.ie" },
]
description = "Alpha shape defined colourspace for automated growth rate determination in multiplexed images of macroalgal discs"
readme = "README.md"
license = { file="LICENSE.txt" }
requires-python = "==3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]
dependencies = [
    ["numpy", "scipy", "scikit-image", "matplotlib", "wxpython"]
]

[project.urls]
"Homepage" = "https://github.com/marcusmchale/algrow"