[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "algrow"
version = "0.6.0"
authors = [
  { name="Marcus McHale", email="marcus.mchale@universityofgalway.ie" },
]
description = "Image segmentation using alpha hulls, plus automated annotation and growth analysis"
readme = "README.md"
license = { file="LICENSE.txt" }
requires-python = ">=3.9"  # tested with 3.9 and 3.10 #todo test with 3.12
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]
dependencies = [
    [  # todo consider pinning these, for now leave it open but haven't really established minimum versions
        "configargparse",
        "numpy",
        "pandas",
        "scipy",
        "scikit-image",
        "alphashape",
        "matplotlib",
        "open3d"
    ]
]

[project.urls]
"Homepage" = "https://github.com/marcusmchale/algrow"
